services:
  sitl:
    build:
      context: .
      dockerfile: Dockerfile
    # On Apple Silicon this is redundant (it will default to arm64),
    # but keeping it prevents accidental amd64/QEMU builds.
    platform: linux/arm64
    container_name: qadt-ardusitl
    # ENV here is optional—use it only to override Dockerfile defaults.
    # environment:
    #   VEHICLE: "ArduCopter"
    #   FRAME: "quad"
    #   OUT_TARGET: "udp:host.docker.internal:14550"
    #   SIM_SPEEDUP: "1"
    stdin_open: true
    tty: true
    restart: unless-stopped