# Compose file for Google Drive uploads

name: qadt-deployment-drive

services:
  drive:
    <<: *base
    extends:
      file: compose.deployment.yml
      service: base
    container_name: qadt-upload-drive

    command: >
      bash -lc "source /opt/ros/humble/setup.bash &&
      source /home/qadt-deployment/AEAC2026/ros_ws/install/setup.bash &&
      ros2 run google_drive drive_uploader"