# Compose file for perception

name: qadt-deployment-perception

services:

  perception:
    extends:
      file: compose.deployment.yml
      service: base_with_gpu
    container_name: qadt-perception

    command: >
      bash -lc "source /opt/ros/humble/setup.bash &&
      source /home/qadt-deployment/AEAC2026/ros_ws/install/setup.bash"
      
# Note sure what scripts to run
# example: could add "&& ros2 run perception record_svo"