services:
  dev:
    network_mode: "host"
    user: "1000:1000"
    environment:
      DISPLAY: "${DISPLAY}"
      XAUTHORITY: "/home/qadt/.Xauthority"
      QT_QPA_PLATFORM: xcb # Forced x11 rendering so gazebo doesn't crash. Container version of Gazebo doesn't work with wayland
      GDK_BACKEND: x11
    volumes:
      - "${HOME}/.Xauthority:/home/qadt/.Xauthority"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw" # fastest, unix socket
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128" # Render-only DRM node (safe GPU acceleration; no display control)
        # Needed for GPU command submission from container to hardware
