services:
  dev:
    environment:
      DISPLAY: "${DISPLAY:-:0}"
      XAUTHORITY: "/home/qadt/.Xauthority"
      PULSE_SERVER: "unix:${XDG_RUNTIME_DIR}/pulse/native"
    volumes:
      - "${HOME}/.Xauthority:/home/qadt/.Xauthority:ro"
      - "/tmp/.X11-unix:/tmp/.X11-unix"             # fastest, unix socket
      - "${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native"
    # For NVIDIA hosts (you need a specific Docker plugin installed), uncomment:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
    # or add in devcontainer.json runArgs: ["--gpus","all"] only on Linux
