name: qadt-devcontainer
services:
  dev:
    image: ghcr.io/queen-s-aerospace-design-team/devcontainer-px4:latest
    pull_policy: always
    tty: true
    privileged: true
    stdin_open: true
    container_name: qadt-devcontainer
    working_dir: /home/qadt/AEAC2026
    volumes:
      - type: bind
        source: ..
        target: /home/qadt/AEAC2026
      # Forward SSH from host -> container
      - type: bind
        source: ${HOME}/.ssh
        target: /home/qadt/.ssh
        read_only: true
    environment:
      QT_X11_NO_MITSHM: "1"
      # Commented out until I find a reason to use these. Currently, using them make MicroXRCEDDS not correctly report ROS topics.
      # ROS_AUTOMATIC_DISCOVERY_RANGE: "LOCALHOST"
      # ROS_LOCALHOST_ONLY: "1"
      # ROS_DOMAIN_ID: "42"
