services:
  dev:
    network_mode: "host"
    environment:
      DISPLAY: "${DISPLAY}"
      XAUTHORITY: "/home/qadt/.Xauthority"
      PULSE_SERVER: "unix:${XDG_RUNTIME_DIR}/pulse/native"
      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR}"
    volumes:
      - "${HOME}/.Xauthority:/home/qadt/.Xauthority:ro"
      - "/tmp/.X11-unix:/tmp/.X11-unix"             # fastest, unix socket
      - "${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}"
      - "${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native"
      - "/dev/dri:/dev/dri:ro"
    gpus: all
    runtime: nvidia # NEEDED TO RUN GPU APPS

# All prerequistes to use the nivida container toolkit are under the `initialize.sh` script ran upon entering the container.

