services:
  dev:
    network_mode: "host"
    environment:
      DISPLAY: "${DISPLAY}"
      XAUTHORITY: "/home/qadt/.Xauthority"
      PULSE_SERVER: "unix:${XDG_RUNTIME_DIR}/pulse/native"
      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR}"
    volumes:
      - "${HOME}/.Xauthority:/home/qadt/.Xauthority:ro"
      - "/tmp/.X11-unix:/tmp/.X11-unix"             # fastest, unix socket
      - "${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}"
      - "${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native"
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"   # Render-only DRM node (safe GPU acceleration; no display control)
                                                    # Needed for GPU command submission from container to hardware

